version: '3.8'

services:

  provider:
    container_name: oauth-example-provider
    build: ./provider
    command: gunicorn main.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./provider:/usr/src/provider
    expose:
      - 8000

  provider-nginx:
    container_name: oauth-example-provider-nginx
    build: ./provider/nginx
    ports:
      - "8000:8000"
    depends_on:
      - provider

  client:
    container_name: oauth-example-client
    build: ./client
    env_file:
      - client/.env
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - ./client:/usr/src/client
    ports:
      - "80:80"
    depends_on:
      - provider
