version: '3.8'

services:

  provider:
    container_name: oauth-example-provider
    build: ./provider
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./provider:/usr/src/provider
    ports:
      - "8000:8000"

  client:
    container_name: oauth-example-client
    build: ./client
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - ./client:/usr/src/client
    ports:
      - "80:80"
    depends_on:
      - provider
